### ISSUE TITLE
Add a "hello world" example app

### ISSUE THREAD

**Issue by haumacher** [treblereel/three4g#169]
Great library for GWT - how did you build these wrappers? Is there some tooling or is it done by hand? How to you upgrade the wrappers for new versions of three.js? 

To get started, however, it would be nice to have a hello world app that uses three4g in an absolutely minimalistic way. The link to the demo pages is broken, don't know, if something like that could have been found there. 

I composed such a app that translates the cube example from https://threejsfundamentals.org/threejs/lessons/threejs-fundamentals.html to GWT: https://github.com/haumacher/hello-three4g

Maybe you could integrated it to your project, or just link it from the README?

**Comment by treblereel** [comment]
Thanks a million for your interest, 
sure, you can push it as separate module under somemeting like hello-three4g :)
are you talking about this demo ? https://env-7073819.cloud-fr1.unispace.io/

right now i am working on j2cl version, it's going to be very cool and fast, after my j2cl quake2 port i think, j2cl is the best option

**Comment by haumacher** [comment]
Hi Dmitrii yes I talked about the link to the demo - it was broken in the main README. I fixed it in the pull request #170 together with the integration of my hello-three4g app to the tree4g project.

Could you please give me a hint, how you built these GWT wrapper code? By hand, or is there a tool?

**Comment by treblereel** [comment]
@haumacher thanks, i ll take a look this weekend

**Comment by treblereel** [comment]
@haumacher there are no good or just working jsinterop generators so i did it manually. It was difficult to make initial implementation but it's easy to support. ok, not too difficult :)
